### ISSUE TITLE
Groovy script crashes SUPERSYMMETRY on loading screen

### ISSUE THREAD

**Issue by PapaDaPro** [CleanroomMC/GroovyScript#100]
When I load SUSY up with the groovy script mod on, the game will permanently freeze at exactly 12.50%, while pre initializing the CreativeCore mod. I waited for an entire hour for it to crash or something but it stayed frozen. This is why the two files I’m sending are completely useless. I checked task manager and the amount of cpu and ram being used by Minecraft was frozen too.
However, if I take the groovy script mod out, the game loads perfectly fine until I load into a world or join a server because groovy is a very required mod.

I’m sending my logs folder and my groovy.logs
The latest.log in the logs folder was when I tried it without the groovyscript mod.

[groovy.log](https://github.com/CleanroomMC/GroovyScript/files/13520118/groovy.log)
[logs.zip](https://github.com/CleanroomMC/GroovyScript/files/13520119/logs.zip)

how do I fix this bruh I just wanna play the game

**Comment by brachy84** [comment]
Logs are not helpful. Send debug log with grs installed.

**Comment by brachy84** [comment]
Ill close this because of inactivity.
