### ISSUE TITLE
Crash with LiteLoader (installed as Forge mod)

### ISSUE THREAD

**Issue by sqwyddy** [CleanroomMC/GroovyScript#112]
Steps to reproduce:

- Set up a clean instance (install Minecraft, install Forge)
- Install GroovyScript
- Install LiteLoader (by following [these](https://www.liteloader.com/explore/docs/user:install:forge) instructions to install as a forge mod)
- Attempt to load Minecraft instance

[crash-2024-01-08_16.31.36-client.txt](https://github.com/CleanroomMC/GroovyScript/files/13856511/crash-2024-01-08_16.31.36-client.txt)

**Comment by KorewaLidesu** [comment]
Is there any reason you want to use LiteLoader?

**Comment by sqwyddy** [comment]
There are mods I want to use on LiteLoader that aren't on Forge on 1.12.2.

**Comment by kappa-maintainer** [comment]
Name it

**Comment by KorewaLidesu** [comment]
> This report isn't about any specific litemods, just LiteLoader alone crashing. I'll be sure to file reports as needed if any litemods cause crashes.

If you need any mods from liteloader, please mention here and I will port it to Forge instead. It would better that way.

**Comment by EndangeredNayla** [comment]
The big contenders for most people is TabbyChat which honestly needs a modern port. 

Ill drop the link here

https://github.com/killjoy1221/TabbyChat-2

**Comment by brachy84** [comment]
The cf page says it works for forge
