### ISSUE TITLE
Failed to get block from mod with metadata

### ISSUE THREAD

**Issue by Bezdrom** [CleanroomMC/GroovyScript#123]
![image](https://github.com/CleanroomMC/GroovyScript/assets/76614403/93c7dc68-9497-4b63-ae70-3a7424bba15f)
```groovy
block('enderio:block_buffer', 3)
```

**Comment by brachy84** [comment]
Blocks dont have metadata. What you want is either the item form of the block with `item('enderio:block_buffer', 3)` or the block state with `blockstate('enderio:block_buffer', 3)`
