### ISSUE TITLE
Problem with getting LocalizedName of block ( event.getState().getBlock().getLocalizedName() ) for blocks from mods (but with vanilla this function works perfectly)

### ISSUE THREAD

**Issue by Bezdrom** [CleanroomMC/GroovyScript#124]
![image](https://github.com/CleanroomMC/GroovyScript/assets/76614403/1abd9832-98c3-43a5-88b5-37ee22d627b1)

**Comment by brachy84** [comment]
You cant get the translated name on server side

**Comment by Bezdrom** [comment]
I testing this script in client, but i know i can't get the translated name on server
