### ISSUE TITLE
Groovyscript execution directory? + filepath distance from config directory

### ISSUE THREAD

**Issue by AncientShotgun** [CleanroomMC/GroovyScript#136]
I'm writing a piece of code to handle some recipes and I'd like to read in a JSON file located in the minecraft/config/[arbitraryModName]/ subdirectory of my instance. What is the exact extent of the filepath I would need to input into a File() constructor to successfully reference this file?

**Comment by brachy84** [comment]
`file('config/')` as of grs 1.0.0
