### ISSUE TITLE
Alternative

### ISSUE THREAD

**Issue by Xikaro** [CleanroomMC/GroovyScript#14]
Implement if possible an alternative in GroovyScript

- [ ] [InWorldCrafting](https://www.curseforge.com/minecraft/mc-mods/inworldcrafting)

- [x] [loottweaker](https://www.curseforge.com/minecraft/mc-mods/loottweaker)

- [x] [Contenttweaker](https://www.curseforge.com/minecraft/mc-mods/contenttweaker)

- [ ] [foodtweaker](https://www.curseforge.com/minecraft/mc-mods/foodtweaker)

- [ ] [mechtech](https://www.curseforge.com/minecraft/mc-mods/mechtech)

- [ ] [journeymapstages](https://www.curseforge.com/minecraft/mc-mods/journeymapstages)

- [ ] [ore-stages](https://www.curseforge.com/minecraft/mc-mods/ore-stages)

- [ ] [Item Stages](https://www.curseforge.com/minecraft/mc-mods/item-stages)

- [ ] [Item Stages](https://www.curseforge.com/minecraft/mc-mods/recipe-stages)

- [ ] [packmode](https://www.curseforge.com/minecraft/mc-mods/packmode)

- [ ] [multiblocktweaker](https://www.curseforge.com/minecraft/mc-mods/multiblocktweaker)

**Comment by Gandalf360one** [comment]
[Multiblock Stages)](https://www.curseforge.com/minecraft/mc-mods/multiblock-stages)

**Comment by Turkey9002** [comment]
- [ ] [Initial Inventory](https://www.curseforge.com/minecraft/mc-mods/initial-inventory)

- [ ] [Rocky Tweaks](https://www.curseforge.com/minecraft/mc-mods/rocky-tweaks)

- [ ] [Vanilla Anvil Repair](https://www.curseforge.com/minecraft/mc-mods/vanilla-anvil-repair)

- [ ] [ZSRarity](https://www.curseforge.com/minecraft/mc-mods/zsrarity)

**Comment by Hydrogen897** [comment]
- [ ] [Artisan Workbench](https://www.curseforge.com/minecraft/mc-mods/artisan-worktables)

**Comment by brachy84** [comment]
I added everything to #1 so it will close this.
