### ISSUE TITLE
GTCEu Pack Server Crash

### ISSUE THREAD

**Issue by lesdmark** [CleanroomMC/GroovyScript#15]
When attempting to start a new server it crashes and crash report mentions groovyscript. Removal of groovyscript stops crashes and server starts normally. I am using a Gregtech Jar that was compiled off of Prototypes fix to the Gregtech 2.4.3-beta JAR, otherwise all other files are from the a16b64a release of the pack.
[crash-2022-10-31_20.05.05-server.txt](https://github.com/CleanroomMC/GroovyScript/files/9905735/crash-2022-10-31_20.05.05-server.txt)

**Comment by brachy84** [comment]
"Fixed in dev"

**Comment by lesdmark** [comment]
Fantastic. I will close the issue then.
