### ISSUE TITLE
Crash durinh iniatilizing

### ISSUE THREAD

**Issue by javiburatos** [CleanroomMC/GroovyScript#153]
[crash-2024-04-02_21.06.15-client.txt](https://github.com/CleanroomMC/GroovyScript/files/14843190/crash-2024-04-02_21.06.15-client.txt)

**Comment by WaitingIdly** [comment]
this is an issue with [TC4Research](https://github.com/Wong-Innovations/TC4Research)'s GroovyScript compat, not with GroovyScript itself. You should bring this issue up over there.

**Comment by javiburatos** [comment]
ok, I have already contacted the developer of the mod and he is informed about it, thank you
