### ISSUE TITLE
I can't copy

### ISSUE THREAD

**Issue by skrjii** [CleanroomMC/GroovyScript#160]
![{A81400C2-CB79-4958-BE09-D83E5B45FE3F}](https://github.com/CleanroomMC/GroovyScript/assets/114705130/0bdb9897-d41d-42d7-b4f7-52b722ba3611)

**Comment by brachy84** [comment]
Send debug log

**Comment by skrjii** [comment]
https://mclo.gs/t9V9v9h

**Comment by brachy84** [comment]
The full log please

**Comment by skrjii** [comment]
https://mclo.gs/gK5Zg5L     in the 9977

**Comment by WaitingIdly** [comment]
whats the minimum set of mods that are required to reproduce this? can you narrow it down?

a side thought: could you run your instance with `-Dmixin.debug.export=true` and share the code inside `.mixin.out/class/net/minecraft/client/gui/GuiScreen.class`? this is specifically checking to see if the `GuiScreenMixin` that GroovyScript adds to intercept and parse the custom chat click-to-copy stuff remains as it should be.

**Comment by IntegerLimit** [comment]
We have the same problem in Nomi-CEu. In our case, my instance mixin output doesn't even show `GuiScreen.class`... very concerning.

**Comment by IntegerLimit** [comment]
Tracing it in the `debug.log`, looks like `GuiScreen` was found. Seems to be that mixin can't find either the injection point or the method.

**Comment by IntegerLimit** [comment]
```
[10:10:41] [main/ERROR] [mixin]: Critical problem: mixin.groovyscript.json:GuiScreenMixin from mod unknown-owner target net.minecraft.client.gui.GuiScreen was loaded too early.
```

Found that error in the log.

**Comment by IntegerLimit** [comment]
```
[10:10:41] [main/ERROR] [mixin]: Critical problem: mixins.tweaks.misc.commands.seed.json:UTCopySeedMixin from mod unknown-owner target net.minecraft.client.gui.GuiScreen was loaded too early.
```
Hmm... similar problem with UT's mixin towards GuiScreen.
