### ISSUE TITLE
Mod Crashed when existing with JAOPCA 2.3.9.19

### ISSUE THREAD

**Issue by EdwinYoungSteve** [CleanroomMC/GroovyScript#161]
![image](https://github.com/CleanroomMC/GroovyScript/assets/99588600/3cf9236a-06cd-45e4-abf9-4b424fb9447d)

**Comment by mczph** [comment]
Use the newest version of JAOPCA

**Comment by AlliSite** [comment]
Use the newest version of JAOPCA.
