### ISSUE TITLE
[Mod Compat]Hope Grs can support Mana Infusion Recipe for making any catalyst cube in Botania Mod

### ISSUE THREAD

**Issue by EdwinYoungSteve** [CleanroomMC/GroovyScript#164]
There are many Catalyst blocks in the Botania Mod, in addition to the Botania itself, there is also Terra Catalyst from the Botanic Additions Mod; And Dimensional Catalyst for ExtraBotany Mod.

Based on this, I expect GroovyScript to support custom mana catalytic infusion recipes of any kind, which can be used by Modpacker to add some more advanced special catalytic blocks.

Some catalytic blocks in my modpack:
![image](https://github.com/CleanroomMC/GroovyScript/assets/99588600/99ebbff3-07db-45a9-bf37-db87b1016603)

My heartfelt thanks.

P.S. I don't speak English very well, so I am using a translation software, so there may be grammatical errors, please understand:(

**Comment by WaitingIdly** [comment]
you absolutely can! the two normal catalysts have inbuilt methods, such as `.useConjuration()`, but *any* block can be passed in as a catalyst - for instance, heres vanilla stone as a catalyst:
```
mods.botania.mana_infusion.recipeBuilder()
    .input(ore('ingotGold'))
    .output(item('botania:manaresource', 1))
    .mana(500)
    .catalyst(blockstate('minecraft:stone'))
    .register()
```
simply replace what blockstate is referenced with a blockstate of your choice.
you can read more about mana infusion on the [wiki](https://cleanroommc.com/groovy-script/mods/botania/mana_infusion).

**Comment by EdwinYoungSteve** [comment]
thanks, I've ignored it:(
