### ISSUE TITLE
[Mod Compat] Latest version of AE2-UEL produces a NPE for inscriber recipes

### ISSUE THREAD

**Issue by glektarssza** [CleanroomMC/GroovyScript#172]
The latest version of [AE2-UEL/Applied-Energistics-2](https://github.com/AE2-UEL/Applied-Energistics-2) is incompatible due to changes in the API.

The change occurred in [PR#430](https://github.com/AE2-UEL/Applied-Energistics-2/pull/430). The `withTopOptional` and `withBottomOptional` methods in `src/api/java/appeng/api/features/IInscriberRecipeBuilder.java` now accept a `Collection<ItemStack>` instead of a flat `ItemStack`.

Not sure if there's any desire to fix this issue (since AE2-UEL is, as the name implies, an unofficial extended life fork) but if there is I'd be happy to try my hand at making the fix myself.

**Comment by WaitingIdly** [comment]
resolved in https://github.com/AE2-UEL/Applied-Energistics-2/pull/464

**Comment by glektarssza** [comment]
I'll check tonight and confirm.

**Comment by glektarssza** [comment]
Looks good using the built JAR from that PR merge. Closing this ticket.
