### ISSUE TITLE
1.01 Server Crashes

### ISSUE THREAD

**Issue by zfms4188** [CleanroomMC/GroovyScript#175]
log: https://pastebin.com/adYnEAAq
ae2-uel: https://github.com/AE2-UEL/Applied-Energistics-2
server: https://github.com/Luohuayu/CatServer/tree/1.12.2

The server crashes when starting, which is not an issue when using version 0.6.4.

**Comment by WaitingIdly** [comment]
duplicate of https://github.com/CleanroomMC/GroovyScript/issues/170, fixed in dev
