### ISSUE TITLE
mek v10 crash

### ISSUE THREAD

**Issue by zfms4188** [CleanroomMC/GroovyScript#181]
log: https://pastebin.com/755bVmiA
mek: https://github.com/sddsd2332/Mekanism-CE-Unofficial-1.12.2
gs: groovyscript-1.1.0-hotfix1

Crashed while starting the server.

**Comment by WaitingIdly** [comment]
this was an issue with Mekanism CE-Unofficial, not GroovyScript, and it was resolved on their end.
