### ISSUE TITLE
Grs Inworldcrafting don't have options that do not consume fluids

### ISSUE THREAD

**Issue by EdwinYoungSteve** [CleanroomMC/GroovyScript#182]
The original InWorldCrafting MOD allows you To set Fluid To Item to be synthesized without consuming fluid, but Grs does not have this feature.

**Comment by WaitingIdly** [comment]
it does not have a simple boolean, but using `afterRecipe` can allow you to set the blockstate to the input fluid - for instance, `.afterRecipe{ World world, BlockPos pos -> world.setBlockState(pos, blockstate('minecraft:water'))})`
