### ISSUE TITLE
Competition with JAOPCA

### ISSUE THREAD

**Issue by code-onigiri** [CleanroomMC/GroovyScript#188]
## mod
- [GroovyScript](https://modrinth.com/mod/GJaDRTrb)
- [JAOPCA](https://modrinth.com/mod/P48mHi2j)
- [MixinBooter](https://modrinth.com/mod/G1ckZuWK)
- [WrapUp](https://modrinth.com/mod/vlot89Sj)
## error log
https://mclo.gs/78zykPl

**Comment by WaitingIdly** [comment]
this is not an error with GroovyScript, but an error with JAOPCA

**Comment by code-onigiri** [comment]
> this is not an error with GroovyScript, but an error with JAOPCA

OK, I will write an issue to JAOPCA.

**Comment by WaitingIdly** [comment]
resolved on their end two weeks ago with this commit https://github.com/TheLMiffy1111/JAOPCA/commit/ba02b9f6802d97d21fe64b7fc10b993ba422b63f
