### ISSUE TITLE
can't reloading

### ISSUE THREAD

**Issue by skrjii** [CleanroomMC/GroovyScript#211]
runConfig

https://mclo.gs/1JYqjRl

Groovy Log

https://mclo.gs/ZEVnBqE

latest log

https://mclo.gs/Cf9369C

first

https://mclo.gs/Qn3sMor

second

https://mclo.gs/1nx735w

and I do /gs deleteScriptCache before reload
![b1b252390256577ca83a6d41eed7873b](https://github.com/user-attachments/assets/064fb36b-6211-43e8-b418-09f860730994)

grs:1.1.2 
cleanroom:0.2.2

**Comment by skrjii** [comment]
If I change the file name then it works
belike 
inworldcraft> inworldcraft1

**Comment by brachy84** [comment]
Im starting to hate cleanroom

**Comment by skrjii** [comment]
> 我开始讨厌洁净室


can't work on cleanroom?

**Comment by brachy84** [comment]
It's supposed to work, but there are a few issues we just cant figure out. And they are all extremly weird.

**Comment by brachy84** [comment]
I cant reproduce this issue

**Comment by skrjii** [comment]
I update crl0.2.3 and Fugue1.60
it fix
