### ISSUE TITLE
VSCode extension seizure

### ISSUE THREAD

**Issue by Pixelguru26** [CleanroomMC/GroovyScript#233]
After attaching Visual Studio Code to the language server, any attempt to edit, view, lightly breathe on, or exist alongside GS files causes rapid-fire errors to display in the notifications and suggestions (from the extension) to stop working entirely.

Attached is the error log from a typical session.
[Vibes Busted.log](https://github.com/user-attachments/files/16811277/Vibes.Busted.log)

**Comment by brachy84** [comment]
Im curently reworking some parts of the language server. Until then you can use the jar i posted yesterday in the discord. (Someone else had the same issue)

**Comment by Pixelguru26** [comment]
Oh, excellent! Thank you very much, I didn't know if this would even be doable, let alone so quickly. Also really glad to hear this mod is still in development, a lot of 1.12.2 has died off lately, leaving some of us a bit stranded.
