### ISSUE TITLE
MekCEu can not make a recipe

### ISSUE THREAD

**Issue by sekinon-maru9** [CleanroomMC/GroovyScript#247]
I use DeepL translation as I'm not English native.

I get an error when I try to add a recipe for PRC in MekCEu.
I use example PRC recipe.
https://cleanroommc.com/groovy-script/mods/mekanism/pressurized_reaction_chamber

error log

> An exception occurred while running scripts. Look at latest.log for a full stacktrace:
> 
> 	groovy.lang.MissingPropertyException: No such property: pressurized_reaction_chamber for class: mekanism.common.integration.groovyscript.MekanismAdd
> Possible solutions: pressurizedReactionChamber
> 		at postInit.mekanism.run(mekanism.groovy:12)
> 		at com.cleanroommc.groovyscript.sandbox.GroovySandbox.runScript(GroovySandbox.java:167)
> 		at com.cleanroommc.groovyscript.sandbox.GroovyScriptSandbox.runScript(GroovyScriptSandbox.java:181)
> 		at com.cleanroommc.groovyscript.sandbox.GroovySandbox.loadScripts(GroovySandbox.java:140)

**Comment by WaitingIdly** [comment]
GroovyScript provides support for base Mekanism, and Mekanism CEu. any issues with compatibility are on Mekanism CEu's end, and you should open an issue on their repository.

**Comment by brachy84** [comment]
sowwy it was our fault
