### ISSUE TITLE
Crash when updating to 1.2.0 (and hotfix version)

### ISSUE THREAD

**Issue by mczph** [CleanroomMC/GroovyScript#263]
https://mclo.gs/ye7T0sm

**Comment by brachy84** [comment]
Some mod you are using still uses old grs compat classes. Find the mod, and report to them

**Comment by WaitingIdly** [comment]
i believe this is fixed via an update to TweakedLib, specifically from 2.0.0 -> 2.0.1
https://github.com/Srdjan-V/TweakedPetroleum/issues/11
