### ISSUE TITLE
CCL Crash exception whilst rendering an item

### ISSUE THREAD

**Issue by jude123412** [CleanroomMC/GroovyScript#264]
Registering new Textures using Any GregTech Renderer causes this to happen when I try and use that texture for a Machine/Multi

This file is the Multiblock script file.
[GTHHMetaTileEntityPreciseAssembler.txt](https://github.com/user-attachments/files/17518767/GTHHMetaTileEntityPreciseAssembler.txt)

This file is the Textures file
[GTHHTextures.txt](https://github.com/user-attachments/files/17518768/GTHHTextures.txt)

This is the most recent Crash Report caused by this
[crash-2024-10-25_09.18.14-client.txt](https://github.com/user-attachments/files/17518582/crash-2024-10-25_09.18.14-client.txt)

I'm not sure if this is a bug with Groovy Script or GregTech or not a bug and I have just missed a step, any help trying to solve this is much appreciated.

**Comment by brachy84** [comment]
Congrats, you are the about the 1000th person who has this issue, but the first one who created a gh issue for it.
I dont think anyone has solved the problem yet. Ill take a look when i have time.

**Comment by brachy84** [comment]
Fixed in 2341ccc
