### ISSUE TITLE
Incorrect error from Error Catcher

### ISSUE THREAD

**Issue by ghzdude** [CleanroomMC/GroovyScript#270]
if you have an event/closure like:
```groovy
mods.gregtech.materialEvent {
  method(, arg1, arg2)
}
```
the error incorrectly points to `{` as the issue, instead of the errant comma in `method()` 
```
org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
  Unexpected input: '{'
  mods.gregtech.materialEvent {
                              ^
```

**Comment by brachy84** [comment]
Groovy issue. Not really anything i can do about it

**Comment by brachy84** [comment]
Took a deeper look and can confirm that fixing this issue might be impossible without fundamentaly changing the parser
