### ISSUE TITLE
Recipe Unloading Doesn't Work (Sandbox Branch)

### ISSUE THREAD

**Issue by Antinoe** [CleanroomMC/GroovyScript#32]
In the Sandbox branch, recipes loaded in by Groovy just won't unload when removed and reloaded.

**Comment by brachy84** [comment]
what

**Comment by Antinoe** [comment]
I'm not exactly sure when this started, but with the latest changes of Groovy Script, added recipes will not unload when commenting them out or removing them from ``.groovy`` files.
