### ISSUE TITLE
Crash when mekV10 and grs are installed together, the following log

### ISSUE THREAD

**Issue by kierkking** [CleanroomMC/GroovyScript#39]
https://mclo.gs/GemUX5N

**Comment by sddsd2332** [comment]
Already fixed in [MEK-1.12.2-v10](https://github.com/sddsd2332/MEK-1.12.2-v10/commit/92ffe2b817d580ca403758b709d8295caa1ad0f0), [Close both sides at the same time](https://github.com/sddsd2332/MEK-1.12.2-v10/issues/21)
