### ISSUE TITLE
[SUGGESTION] "Check" command

### ISSUE THREAD

**Issue by Shazuli** [CleanroomMC/GroovyScript#44]
**Hi**

I'm notorious for doing syntax errors. It would be nice with a command similar to [CraftTweaker](https://docs.blamejared.com/1.12/en/Vanilla/Commands#syntax) to just check the syntax of all the scripts. Reloading takes a bit to do (especially with a large amount of scripts and some slow functions in conjunction). And scripts in `preInit` only runs once at startup so I don't get any errors unless I close and load the game and sees in either the console and have to spam-click exiting Minecraft or when I join a world and sees the error in chat.
So something like: `/gs check preInit` or  `/gs check postInit/<scriptName.groovy>` or something. Or just `/gs check` to check all scripts under `groovy/`.

**Comment by brachy84** [comment]
Implemented in [0.4.5](https://github.com/CleanroomMC/GroovyScript/releases/tag/v0.4.5). You can now use /gs check and it will compile, but not run all load stages. With small scripts i found that time is similar to reloading the postInit stage (just the reloading without jei).
