### ISSUE TITLE
Unable to craft registered recipes in the Arcane Workbench

### ISSUE THREAD

**Issue by Shazuli** [CleanroomMC/GroovyScript#48]
***Hi***

I am unable to craft recipes registered for the Arcane Workbench in GroovyScript. They do show up in JEI/HEI, but even with the research, Vis and crystals I'm unable to craft it. I tried the suggested recipe too from the docs, but it didn't work either.
```groovy
mods.thaumcraft.ArcaneWorkbench.shapedBuilder()
        .researchKey('UNLOCKALCHEMY@3')
        .output(item('minecraft:pumpkin'))
        .row('SS ')
        .row('   ')
        .row('   ')
        .key('S', item('minecraft:pumpkin_seeds'))
        .aspect(aspect('terra'))
        .vis(5)
        .register()
```

I was unable to show these recipes in the Thaumonomicon too. At first I assumed it was because the registry id was something else, so I did a dump on the registry and found it was something like `groovyscript:shaped_arcane_ffffffff`. I inserted that into the research config and reloaded the Jsons, but it still didn't show up.

A `/gs reload` also showed me that the registry id changed too (`groovyscript:shaped_arcane_ffffffff` -> `groovyscript:shaped_arcane_fffffffe`), making the Jsons invalid again. Restarting the game made it go back to `ffffffff`. So perhaps an additional method in the builder to supply a registry id would be nice.

**Comment by Rongmario** [comment]
Calling `.name(...)` should work in supplying a custom registry id.

**Comment by Shazuli** [comment]
Looks like passing `name()` into the builder worked. I am still however unable to craft it.

**Comment by brachy84** [comment]
Fixed on master
