### ISSUE TITLE
Crash with Loot Overhaul

### ISSUE THREAD

**Issue by Invadermonky** [CleanroomMC/GroovyScript#75]
### Steps to reproduce: ###
* Install [GroovyScript](https://www.curseforge.com/minecraft/mc-mods/groovyscript)
* Install [Loot Overhaul](https://www.curseforge.com/minecraft/mc-mods/loot-overhaul)
* Attempt to load Minecraft instance

[crash-2023-07-13_16.16.36-client.txt](https://github.com/CleanroomMC/GroovyScript/files/12045082/crash-2023-07-13_16.16.36-client.txt)

**Comment by brachy84** [comment]
Is this still happening with 0.6.1?

**Comment by Invadermonky** [comment]
Sorry for the late response, cleaning up my old issue list.

Tested this with GS version 0.7.3 in a large modpack and this crash appears to be fixed.
