### ISSUE TITLE
Agricraft config go in depth with groovy script

### ISSUE THREAD

**Issue by ferreiraalex** [CleanroomMC/GroovyScript#84]
I use 0.5.2
Its hard to find what happens, but I find if I add groovy 
Go depth after all game start, I update to 0.6.1
This happens too
I found this 
https://github.com/AgriCraft/AgriCraft/issues/1208
when I Google this issue. Its the same but its 2019
But for me with groovy I have depth without no

**Comment by ferreiraalex** [comment]
![explorer_utsGHFTFIN](https://github.com/CleanroomMC/GroovyScript/assets/10839855/f6349ec1-87c3-4f22-8ed9-9c840633fc6f)

**Comment by brachy84** [comment]
WTF :concern:
